# Generated by Django 5.0.6 on 2024-06-21 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android', '0003_user_balance_user_planing_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddExpenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AddIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
