# Generated by Django 5.0.6 on 2024-06-21 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android', '0005_addexpenditure_user_addincome_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addincome',
            name='categories',
        ),
        migrations.AddField(
            model_name='addexpenditure',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='android.categories'),
        ),
    ]
