# Generated by Django 5.0.6 on 2024-06-21 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android', '0006_remove_addincome_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpInc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='addincome',
            name='user',
        ),
        migrations.RemoveField(
            model_name='limitations',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='limitations',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='user',
            name='planing_balance',
        ),
        migrations.CreateModel(
            name='Planing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='AddExpenditure',
        ),
        migrations.DeleteModel(
            name='AddIncome',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Limitations',
        ),
    ]
