# Generated by Django 5.0.6 on 2024-06-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android', '0007_expinc_remove_addincome_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expinc',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='expinc',
            name='money',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='planing',
            name='cafe',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='planing',
            name='dosug',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='planing',
            name='home',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='planing',
            name='obraz',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='planing',
            name='plan_balance',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='planing',
            name='podar',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='planing',
            name='product',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='planing',
            name='tochki',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='planing',
            name='zdor',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.IntegerField(null=True),
        ),
    ]
