# Generated by Django 5.0.6 on 2024-06-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android', '0008_expinc_date_expinc_money_planing_cafe_planing_dosug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('images', models.CharField(max_length=40)),
            ],
        ),
    ]
