# Generated by Django 5.0.6 on 2024-06-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android', '0009_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planing',
            name='cafe',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='planing',
            name='dosug',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='planing',
            name='home',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='planing',
            name='obraz',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='planing',
            name='plan_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='planing',
            name='podar',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='planing',
            name='product',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='planing',
            name='tochki',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='planing',
            name='zdor',
            field=models.IntegerField(default=0),
        ),
    ]
