# Generated by Django 5.0.6 on 2024-06-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android', '0010_alter_planing_cafe_alter_planing_dosug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planing',
            name='budget',
            field=models.IntegerField(default=0),
        ),
    ]
