# Generated by Django 5.0.6 on 2024-06-21 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android', '0011_planing_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='expinc',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
