# Generated by Django 5.0.6 on 2024-06-21 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android', '0012_expinc_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategExp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zdor', models.IntegerField(default=0)),
                ('home', models.IntegerField(default=0)),
                ('cafe', models.IntegerField(default=0)),
                ('dosug', models.IntegerField(default=0)),
                ('obraz', models.IntegerField(default=0)),
                ('podar', models.IntegerField(default=0)),
                ('product', models.IntegerField(default=0)),
                ('tochki', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
