# Generated by Django 5.0.6 on 2024-06-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android', '0013_categexp'),
    ]

    operations = [
        migrations.AddField(
            model_name='expinc',
            name='categori',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
